package main

import (
	"fmt"
	"os"
	"os/exec"
)

func main() {
	// The C code generated by Fox
	cCode := `
#include <stdio.h>
int main() {
    printf("Hello from Fox via TCC CLI on Mac M1!\n");
    return 0;
}
`

	// 1. Prepare the command to run the local TCC
	// Use "./tcc" to run the binary in the current folder
	libPath := "/Users/fedora/repo/tinycc"
	cmd := exec.Command("../../tinycc/tcc", "-B"+libPath, "-run", "-")

	// 2. Pass the library path environment variable
	cmd.Env = append(os.Environ(), "TCC_LIB_PATH=/Users/fedora/repo/tinycc")

	// 3. Setup pipes for input and output
	stdin, err := cmd.StdinPipe()
	if err != nil {
		fmt.Println("Failed to create stdin pipe:", err)
		return
	}

	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	// 4. Start the process
	err = cmd.Start()
	if err != nil {
		fmt.Println("Failed to start TCC process:", err)
		return
	}

	// 5. Feed the C code to TCC's stdin
	_, err = stdin.Write([]byte(cCode))
	if err != nil {
		fmt.Println("Failed to write to stdin:", err)
		return
	}
	stdin.Close()

	// 6. Wait for execution
	fmt.Println("--- TCC Output ---")
	err = cmd.Wait()
	if err != nil {
		fmt.Printf("Execution finished with error: %v\n", err)
	}
}
