package cgen

import (
	"bytes"
	"fmt"
	"strings"

	"fox/aster"
	"fox/symbols"
)

type Codegen struct {
	symbolTable      *symbols.SymbolTable
	sourceStream     bytes.Buffer
	unit             *aster.AST
	project          *aster.Project
	indent           int
	CurrentFunction  *aster.Func
	definedEnvelopes map[string]bool
}

func NewCodegen(proj *aster.Project) *Codegen {
	var firstUnit *aster.AST
	if len(proj.Packages) > 0 && len(proj.Packages[0].Files) > 0 {
		firstUnit = &aster.AST{
			Decls: proj.Packages[0].Files[0].Decls,
		}
	}

	activeTable := proj.SymbolTable
	if activeTable == nil {
		activeTable = symbols.NewSymbolTable(nil)
	}

	return &Codegen{
		unit:             firstUnit,
		project:          proj,
		symbolTable:      activeTable,
		definedEnvelopes: make(map[string]bool),
	}
}

func (cg *Codegen) Generate() string {
	if cg.unit == nil {
		panic("Codegen unit is nil!")
	}

	cg.sourceStream.Reset()

	cg.sourceStream.WriteString("// Code generated by Fox Compiler (Explicit Logic). DO NOT EDIT.\n")
	cg.sourceStream.WriteString("#include <stdio.h>\n")
	cg.sourceStream.WriteString("#include <stdint.h>\n")
	cg.sourceStream.WriteString("#include <stdbool.h>\n")
	cg.sourceStream.WriteString("#include <stdlib.h>\n")
	cg.sourceStream.WriteString("#include \"../foxgc/fgc.h\"\n\n")

	cg.sourceStream.WriteString("// Forward Declarations\n")
	for _, decl := range cg.unit.Decls {
		if d, ok := decl.(*aster.Struct); ok {
			fmt.Fprintf(&cg.sourceStream, "typedef struct %s %s;\n", d.Name, d.Name)
		}
		if d, ok := decl.(*aster.EnumDecl); ok {
			fmt.Fprintf(&cg.sourceStream, "typedef struct %s %s;\n", d.Name, d.Name)
		}
	}
	cg.sourceStream.WriteString("\n")

	cg.sourceStream.WriteString("// Base User Structs & Enums\n")
	for _, decl := range cg.unit.Decls {
		if d, ok := decl.(*aster.Struct); ok {
			// تجنب إعادة طباعة هياكل المساعدة الضمنية هنا إذا كانت ضمن Decls
			if len(d.Name) < 5 || d.Name[:5] != "_res_" {
				cg.genStruct(d)
			}
		}
		if d, ok := decl.(*aster.EnumDecl); ok {
			cg.genEnumDecl(d)
		}
	}

	cg.sourceStream.WriteString("// Helper Multi-Return Structs\n")
	cg.genResultEnvelopes()

	cg.sourceStream.WriteString("// Function Prototypes\n")
	for _, decl := range cg.unit.Decls {
		if f, ok := decl.(*aster.Func); ok {
			cg.genFunctionPrototype(f)
		}
	}
	cg.sourceStream.WriteString("\n")

	cg.sourceStream.WriteString("// Global Variables & Function Implementations\n")
	for _, decl := range cg.unit.Decls {
		switch d := decl.(type) {
		case *aster.VarDeclar:
			cg.genGlobalVar(d)
		case *aster.Func:
			cg.genFunction(d)
		}
	}

	return cg.sourceStream.String()
}
func (cg *Codegen) getEnvelopeName(funcName string) string {
	return "_res_" + funcName
}

func (cg *Codegen) genResultEnvelopes() {
	for _, decl := range cg.unit.Decls {
		if f, ok := decl.(*aster.Func); ok && f.Return != nil && len(f.Return.Fields) > 0 {
			if len(f.Return.Fields) == 1 && !f.Return.HasError {
				continue
			}

			envelopeName := cg.getEnvelopeName(f.FuncName)
			if cg.definedEnvelopes[envelopeName] {
				continue
			}
			cg.definedEnvelopes[envelopeName] = true

			fmt.Fprintf(&cg.sourceStream, "typedef struct %s {\n", envelopeName)
			for i, field := range f.Return.Fields {
				cType := cg.mapType(field.Type)

				// gen default field name
				fieldName := field.Name
				if fieldName == "" {
					fieldName = fmt.Sprintf("_%d", i)
				}

				fmt.Fprintf(&cg.sourceStream, "    %s %s;\n", cType, fieldName)
			}
			if f.Return.HasError {
				fmt.Fprintf(&cg.sourceStream, "    char* err;\n")
			}
			fmt.Fprintf(&cg.sourceStream, "} %s;\n\n", envelopeName)
		}
	}
}

func (cg *Codegen) genStruct(s *aster.Struct) {
	fmt.Fprintf(&cg.sourceStream, "struct %s {\n", s.Name)
	for _, field := range s.Fields {
		cType := cg.mapType(field.Type)
		prefix := ""
		if field.Type != nil && field.Type.PtrDepth > 0 && field.Type.Name == s.Name {
			prefix = "struct "
		}
		if field.Type != nil && field.Type.IsArray {
			fmt.Fprintf(&cg.sourceStream, "    %s%s %s[%d];\n", prefix, cType, field.Name, field.Type.Size)
		} else {
			fmt.Fprintf(&cg.sourceStream, "    %s%s %s;\n", prefix, cType, field.Name)
		}
	}
	fmt.Fprintf(&cg.sourceStream, "};\n\n")
}

func (cg *Codegen) genEnumDecl(enum *aster.EnumDecl) {
	fmt.Fprintf(&cg.sourceStream, "struct %s {\n", enum.Name)
	fmt.Fprintf(&cg.sourceStream, "    int32_t _tag;\n")
	fmt.Fprintf(&cg.sourceStream, "    union {\n")

	for _, variant := range enum.Variants {
		if len(variant.Fields) > 0 {
			fmt.Fprintf(&cg.sourceStream, "        struct {\n")
			for _, field := range variant.Fields {
				cType := cg.mapType(field.Type)
				prefix := ""
				if field.Type != nil && field.Type.PtrDepth > 0 && field.Type.Name == enum.Name {
					prefix = "struct "
				}
				if field.Type != nil && field.Type.IsArray {
					fmt.Fprintf(&cg.sourceStream, "            %s%s %s[%d];\n", prefix, cType, field.Name, field.Type.Size)
				} else {
					fmt.Fprintf(&cg.sourceStream, "            %s%s %s;\n", prefix, cType, field.Name)
				}
			}
			fmt.Fprintf(&cg.sourceStream, "        } %s;\n", variant.Name)
		}
	}

	fmt.Fprintf(&cg.sourceStream, "    } variants;\n")
	fmt.Fprintf(&cg.sourceStream, "};\n\n")
}

func (cg *Codegen) genFunctionPrototype(f *aster.Func) {
	retType := cg.getFuncReturnType(f)
	fmt.Fprintf(&cg.sourceStream, "%s %s(", retType, f.FuncName)
	for i, p := range f.Params {
		pType := cg.mapType(p.Type)
		fmt.Fprintf(&cg.sourceStream, "%s %s", pType, p.Name)
		if i < len(f.Params)-1 {
			cg.sourceStream.WriteString(", ")
		}
	}
	cg.sourceStream.WriteString(");\n")
}

func (cg *Codegen) genGlobalVar(decl *aster.VarDeclar) {
	cType := cg.mapType(decl.Type)
	fmt.Fprintf(&cg.sourceStream, "%s %s;\n", cType, decl.Name)
}

func (cg *Codegen) genFunction(f *aster.Func) {
	cg.CurrentFunction = f

	// 1. تحديد نوع الإرجاع: إذا كانت الدالة تمتلك Envelope نستخدم اسمه، وإلا نستخدم النوع العادي
	retType := cg.getFuncReturnType(f)
	//	if f.ReturnEnvelope != nil {
	//		retType = f.ReturnEnvelope.Name
	//	}

	fmt.Fprintf(&cg.sourceStream, "%s %s(", retType, f.FuncName)
	for i, p := range f.Params {
		pType := cg.mapType(p.Type)
		fmt.Fprintf(&cg.sourceStream, "%s %s", pType, p.Name)
		if i < len(f.Params)-1 {
			cg.sourceStream.WriteString(", ")
		}
	}
	cg.sourceStream.WriteString(") {\n")

	cg.indent++

	// 2. تهيئة الـ Stack / GC في بداية main
	if f.FuncName == "main" {
		cg.writeIndent()
		fmt.Fprintf(&cg.sourceStream, "int32_t stack_top_anchor;\n")
		cg.writeIndent()
		fmt.Fprintf(&cg.sourceStream, "fgc_init(&stack_top_anchor);\n")
	}

	// 3. تصريح متغيرات الإرجاع الأصلي في أول سطر من جسم الدالة
	if f.Return != nil && len(f.Return.Fields) > 0 {
		for i, field := range f.Return.Fields {
			fieldName := field.Name
			if fieldName == "" {
				fieldName = fmt.Sprintf("v%d", i)
			}

			cg.writeIndent()
			fType := cg.mapType(field.Type)
			if field.Type.PtrDepth > 0 {
				fmt.Fprintf(&cg.sourceStream, "%s %s = NULL;\n", fType, fieldName)
			} else {
				fmt.Fprintf(&cg.sourceStream, "%s %s = {0};\n", fType, fieldName)
			}
		}
	}

	// 4. طباعة أسطر جسم الدالة
	if f.Body != nil {
		for _, stmt := range f.Body.Stmts {
			cg.genStmt(stmt)
		}
	}

	if f.FuncName == "main" {
		cg.writeIndent()
		cg.sourceStream.WriteString("return 0;\n")
	}

	cg.indent--
	cg.sourceStream.WriteString("}\n\n")

	cg.CurrentFunction = nil
}

func (cg *Codegen) getFuncReturnType(f *aster.Func) string {
	if f.FuncName == "main" {
		return "int"
	}
	if f.Return != nil && len(f.Return.Fields) > 0 {
		if len(f.Return.Fields) == 1 && !f.Return.HasError {
			return cg.mapType(f.Return.Fields[0].Type)
		}
		return cg.getEnvelopeName(f.FuncName)
	}
	return "void"
}

func (cg *Codegen) genCall(e *aster.CallExpr) {
	ident, _ := e.Callee.(*aster.IdentExpr)
	cg.sourceStream.WriteString(ident.Name + "(")
	for i, arg := range e.Args {
		cg.genExpr(arg)
		if i < len(e.Args)-1 {
			cg.sourceStream.WriteString(", ")
		}
	}
	cg.sourceStream.WriteString(")")
}

func (cg *Codegen) genBlock(block *aster.FrameBlock) {
	cg.sourceStream.WriteString("{\n")
	cg.indent++

	for _, stmt := range block.Stmts {
		cg.writeIndent()
		cg.genStmt(stmt)
	}

	cg.indent--
	cg.writeIndent()
	cg.sourceStream.WriteString("}\n")
}

func (cg *Codegen) genHeapStructLiteral(lit *aster.StructLiteral, targetVarName string) {
	rawName := lit.Type.Name
	structName := rawName
	variantName := ""
	isEnumVariant := false

	if strings.Contains(rawName, ".") {
		parts := strings.Split(rawName, ".")
		structName = parts[0]
		variantName = parts[1]
		isEnumVariant = true
	}

	classIdx := cg.calculateClassIndex(structName)
	hasPointers := cg.structHasPointers(structName)
	typeTag := 1

	fmt.Fprintf(&cg.sourceStream, "    %s* %s = (%s*)((char*)fgc_alloc(%d, %d, %d) + 8);\n",
		structName, targetVarName, structName, classIdx, typeTag, hasPointers)

	if isEnumVariant {
		generatedTagValue := 0
		switch variantName {
		case "Active":
			generatedTagValue = 1
		case "Inactive":
			generatedTagValue = 2
		}

		cg.writeIndent()
		fmt.Fprintf(&cg.sourceStream, "%s->_tag = %d;\n", targetVarName, generatedTagValue)

		for _, providedField := range lit.Fields {
			cg.writeIndent()
			fmt.Fprintf(&cg.sourceStream, "%s->variants.%s.%s = ", targetVarName, variantName, providedField.Name)
			cg.genExpr(providedField.Value)
			cg.sourceStream.WriteString(";\n")
		}
	} else {
		for _, providedField := range lit.Fields {
			cg.writeIndent()
			fmt.Fprintf(&cg.sourceStream, "%s->%s = ", targetVarName, providedField.Name)
			cg.genExpr(providedField.Value)
			cg.sourceStream.WriteString(";\n")
		}
	}
}

func (cg *Codegen) genExpr(expr aster.Expression) {
	switch e := expr.(type) {

	case *aster.UnaryExpr:
		fmt.Fprintf(&cg.sourceStream, "%s", e.Op)
		cg.genExpr(e.Expr)

	case *aster.Declar:
		if len(e.Targets) > 0 {
			if ident, ok := e.Targets[0].(*aster.IdentExpr); ok {
				typeName := "int32_t"
				if e.Value != nil {
					isUnwrapped := false
					if call, ok := e.Value.(*aster.CallExpr); ok && call.UnwrapPanic {
						isUnwrapped = true
					} else if bin, ok := e.Value.(*aster.BinaryExpr); ok {
						if leftCall, ok := bin.Left.(*aster.CallExpr); ok && leftCall.UnwrapPanic {
							isUnwrapped = true
						}
						if rightCall, ok := bin.Right.(*aster.CallExpr); ok && rightCall.UnwrapPanic {
							isUnwrapped = true
						}
					}

					if isUnwrapped {
						typeName = "int32_t"
					} else if call, ok := e.Value.(*aster.CallExpr); ok {
						if callIdent, ok := call.Callee.(*aster.IdentExpr); ok && callIdent.Type != nil {
							if strings.HasPrefix(callIdent.Type.Name, "_Result_") {
								typeName = callIdent.Type.Name
							}
						}
					} else if lit, ok := e.Value.(*aster.StructLiteral); ok && lit.Type != nil {
						typeName = lit.Type.Name
					}
				}

				fmt.Fprintf(&cg.sourceStream, "%s %s = ", typeName, ident.Name)
				cg.genExpr(e.Value)
				cg.sourceStream.WriteString(";\n")
			}
		}
	case *aster.StructLiteral:
		fmt.Fprintf(&cg.sourceStream, "(%s){", e.Type.Name)
		for i, field := range e.Fields {
			fmt.Fprintf(&cg.sourceStream, ".%s = ", field.Name)
			cg.genExpr(field.Value)
			if i < len(e.Fields)-1 {
				cg.sourceStream.WriteString(", ")
			}
		}
		cg.sourceStream.WriteString("}")

	case *aster.FieldAccessExpr:
		if ident, ok := e.Object.(*aster.IdentExpr); ok && ident.Type != nil {
			typeName := strings.TrimPrefix(ident.Type.Name, "*")

			if strings.HasPrefix(typeName, "_Result_") {
				separator := "."
				if ident.Type.PtrDepth > 0 {
					separator = "->"
				}

				if e.Field == "msg" || e.Field == "code" {
					fmt.Fprintf(&cg.sourceStream, "%s%svalue.error.%s", ident.Name, separator, e.Field)
				} else {
					fmt.Fprintf(&cg.sourceStream, "%s%svalue.success.%s", ident.Name, separator, e.Field)
				}
				break
			}

			if typeName == "Status" {
				separator := "."
				if ident.Type.PtrDepth > 0 {
					separator = "->"
				}
				variantName := "Active"
				if e.Field == "reason" {
					variantName = "Inactive"
				}
				fmt.Fprintf(&cg.sourceStream, "%s%svariants.%s.%s", ident.Name, separator, variantName, e.Field)
				break
			}
		}

		cg.genExpr(e.Object)
		separator := "."
		if ident, ok := e.Object.(*aster.IdentExpr); ok && ident.Type != nil {
			if ident.Type.PtrDepth > 0 {
				separator = "->"
			}
		}
		fmt.Fprintf(&cg.sourceStream, "%s%s", separator, e.Field)

	case *aster.IntExpr:
		fmt.Fprintf(&cg.sourceStream, "%d", e.Value)

	case *aster.StringExpr:
		fmt.Fprintf(&cg.sourceStream, "\"%s\"", e.Literal)

	case *aster.IdentExpr:
		cg.sourceStream.WriteString(e.Name)

	case *aster.BinaryExpr:
		cg.sourceStream.WriteString("(")
		cg.genExpr(e.Left)
		fmt.Fprintf(&cg.sourceStream, " %s ", e.Op)
		cg.genExpr(e.Right)
		cg.sourceStream.WriteString(")")

	case *aster.CallExpr:
		if e.UnwrapPanic {
			cg.sourceStream.WriteString("({\n")
			cg.indent++

			baseTypeName := "int"
			if ident, ok := e.Callee.(*aster.IdentExpr); ok && ident.Type != nil {
				baseTypeName = strings.TrimPrefix(ident.Type.Name, "_Result_")
			}
			envelopeName := "_Result_" + baseTypeName

			cg.writeIndent()
			fmt.Fprintf(&cg.sourceStream, "%s __tmp_err_env = ", envelopeName)
			cg.genCall(e)
			cg.sourceStream.WriteString(";\n")

			cg.writeIndent()
			cg.sourceStream.WriteString("if (__tmp_err_env.header.error_flag == 1) {\n")
			cg.indent++

			if cg.CurrentFunction != nil && cg.CurrentFunction.Return != nil && cg.CurrentFunction.Return.HasError {
				cg.writeIndent()
				cg.sourceStream.WriteString("return __tmp_err_env;\n")
			} else {
				cg.writeIndent()
				fmt.Fprintf(&cg.sourceStream, "printf(\"Runtime Panic: unhandled error in function main! Message: %%s\\n\", __tmp_err_env.value.error.msg);\n")
				cg.writeIndent()
				cg.sourceStream.WriteString("exit(1);\n")
			}

			cg.indent--
			cg.writeIndent()
			cg.sourceStream.WriteString("}\n")

			cg.writeIndent()
			cg.sourceStream.WriteString("__tmp_err_env.value.success;\n")

			cg.indent--
			cg.writeIndent()
			cg.sourceStream.WriteString("})")
			break
		}

		cg.genCall(e)

	case *aster.IndexExpr:
		cg.genExpr(e.Target)
		cg.sourceStream.WriteString("[")
		cg.genExpr(e.Index)
		cg.sourceStream.WriteString("]")
	}
}

func (cg *Codegen) genStmt(stmt aster.Statement) {
	switch s := stmt.(type) {
	case *aster.IfStmt:
		cg.genIfStmt(s)
	case *aster.MatchStmt:
		cg.genMatchStmt(s)
	case *aster.Declar:
		cg.genDeclarStmt(s)
	case *aster.VarDeclar:
		cg.genVarDeclarStmt(s)
	case *aster.Assign:
		cg.genAssignStmt(s)
	case *aster.ExprStmt:
		cg.genExprStmt(s)
	case *aster.ReturnStmt:
		cg.genReturnStmt(s)
	case *aster.ForStmt:
		cg.genForStmt(s)
	}
}

func (cg *Codegen) genIfStmt(s *aster.IfStmt) {
	cg.writeIndent()
	cg.sourceStream.WriteString("if (")
	cg.genExpr(s.Cond)
	cg.sourceStream.WriteString(") ")

	savedFunc := cg.CurrentFunction

	if s.Then != nil {
		cg.genBlock(s.Then)
	}

	cg.CurrentFunction = savedFunc

	if s.Else != nil {
		cg.sourceStream.WriteString(" else ")
		if block, ok := s.Else.(*aster.FrameBlock); ok {
			cg.genBlock(block)
		} else {
			cg.writeIndent()
			cg.sourceStream.WriteString("{\n")
			cg.indent++
			cg.writeIndent()
			cg.genStmt(s.Else)
			cg.indent--
			cg.writeIndent()
			cg.sourceStream.WriteString("}\n")
		}
	} else {
		cg.sourceStream.WriteString("\n")
	}

	cg.CurrentFunction = savedFunc
}

func (cg *Codegen) genMatchStmt(s *aster.MatchStmt) {
	isErrorEnvelope := false
	var objectIdentName string
	if ident, ok := s.Object.(*aster.IdentExpr); ok && ident.Type != nil {
		objectIdentName = ident.Name
		if strings.HasPrefix(ident.Type.Name, "_Result_") {
			isErrorEnvelope = true
		}
	}

	cg.writeIndent()
	if isErrorEnvelope {
		cg.sourceStream.WriteString("switch (")
		cg.genExpr(s.Object)
		cg.sourceStream.WriteString(".header.error_flag) {\n")
	} else {
		cg.sourceStream.WriteString("switch (")
		cg.genExpr(s.Object)
		cg.sourceStream.WriteString("->_tag) {\n")
	}

	for _, c := range s.Cases {
		tagValue := 0
		isErrorCase := false

		if len(c.Conditions) > 0 {
			if ident, ok := c.Conditions[0].(*aster.IdentExpr); ok {
				if isErrorEnvelope {
					if ident.Name == "Error" {
						isErrorCase = true
						tagValue = 1
					}
				} else {
					switch ident.Name {
					case "Active":
						tagValue = 1
					case "Inactive":
						tagValue = 2
					}
				}
			}
		}

		if isErrorEnvelope && !isErrorCase {
			tagValue = 0
		}

		cg.writeIndent()
		fmt.Fprintf(&cg.sourceStream, "case %d:\n", tagValue)
		cg.indent++

		if c.Body != nil {
			numStmts := len(c.Body.Stmts)
			for idx, subStmt := range c.Body.Stmts {
				if idx == numStmts-1 {
					if exprStmt, ok := subStmt.(*aster.ExprStmt); ok && exprStmt.Expr != nil {
						if call, ok := exprStmt.Expr.(*aster.CallExpr); ok {
							cg.writeIndent()

							isPrintfCall := false
							if callIdent, ok := call.Callee.(*aster.IdentExpr); ok && callIdent.Name == "printf" {
								isPrintfCall = true
							}

							if isErrorEnvelope && !isErrorCase && isPrintfCall {
								fmt.Fprintf(&cg.sourceStream, "printf(")
								if len(call.Args) > 0 {
									cg.genExpr(call.Args[0])
									for k := 1; k < len(call.Args); k++ {
										cg.sourceStream.WriteString(", ")
										if argIdent, ok := call.Args[k].(*aster.IdentExpr); ok && argIdent.Name == objectIdentName {
											fmt.Fprintf(&cg.sourceStream, "%s.value.success", objectIdentName)
										} else {
											cg.genExpr(call.Args[k])
										}
									}
								}
								cg.sourceStream.WriteString("); break;\n")
								continue
							}

							cg.genCall(call)
							cg.sourceStream.WriteString("; break;\n")
							continue
						}
					}
					cg.genStmt(subStmt)
				} else {
					cg.genStmt(subStmt)
				}
			}
		}

		cg.indent--
	}

	if s.Else != nil {
		cg.writeIndent()
		cg.sourceStream.WriteString("default:\n")
		cg.indent++

		for _, subStmt := range s.Else.Stmts {
			if exprStmt, ok := subStmt.(*aster.ExprStmt); ok && exprStmt.Expr != nil {
				if call, ok := exprStmt.Expr.(*aster.CallExpr); ok {
					isPrintfCall := false
					if callIdent, ok := call.Callee.(*aster.IdentExpr); ok && callIdent.Name == "printf" {
						isPrintfCall = true
					}

					if isErrorEnvelope && isPrintfCall {
						cg.writeIndent()
						fmt.Fprintf(&cg.sourceStream, "printf(")
						if len(call.Args) > 0 {
							cg.genExpr(call.Args[0])
							for k := 1; k < len(call.Args); k++ {
								cg.sourceStream.WriteString(", ")
								if argIdent, ok := call.Args[k].(*aster.IdentExpr); ok && argIdent.Name == objectIdentName {
									fmt.Fprintf(&cg.sourceStream, "%s.value.success", objectIdentName)
								} else {
									cg.genExpr(call.Args[k])
								}
							}
						}
						cg.sourceStream.WriteString("); break;\n")
						continue
					}
				}
			}
			cg.writeIndent()
			cg.genStmt(subStmt)
		}

		cg.indent--
	}

	cg.writeIndent()
	cg.sourceStream.WriteString("}\n")
}

func (cg *Codegen) genDeclarStmt(s *aster.Declar) {
	// Ensure there is at least one target in the slice
	if len(s.Targets) == 0 {
		return
	}

	// 1. التعامل مع التفكيك والإسناد المتعدد (Multi-Return Unpacking)
	if callExpr, ok := s.Value.(*aster.CallExpr); ok && len(s.Targets) > 1 {
		funcName := ""
		if callIdent, ok := callExpr.Callee.(*aster.IdentExpr); ok {
			funcName = callIdent.Name
		}

		envelopeName := cg.getEnvelopeName(funcName)
		tmpVar := fmt.Sprintf("_tmp_ret_%d", s.Line)

		//  Struct المساعد الناتج عن الاستدعاء
		cg.writeIndent()
		fmt.Fprintf(&cg.sourceStream, "%s %s = ", envelopeName, tmpVar)
		cg.genExpr(callExpr)
		cg.sourceStream.WriteString(";\n")

		// تفكيك القيم وإسنادها للمتغيرات Target
		for i, target := range s.Targets {
			if ident, ok := target.(*aster.IdentExpr); ok {
				cType := "int32_t"
				if ident.Type != nil && ident.Type.Name != "" && ident.Type.Name != "INVALID" && ident.Type.Name != "invalid" {
					cType = cg.mapType(ident.Type)
				}

				cg.writeIndent()
				fmt.Fprintf(&cg.sourceStream, "%s %s = %s._%d;\n", cType, ident.Name, tmpVar, i)
			}
		}
		return
	}

	// 2. التعامل مع الإعلان والإنشاء المفرد العادي (Single Target Declaration)
	cg.writeIndent()

	if ident, ok := s.Targets[0].(*aster.IdentExpr); ok {
		typeName := "int32_t"

		if ident.Type != nil && ident.Type.Name != "" && ident.Type.Name != "INVALID" && ident.Type.Name != "invalid" {
			typeName = cg.mapType(ident.Type)
		} else if s.Value != nil {
			switch val := s.Value.(type) {
			case *aster.CallExpr:
				if callIdent, ok := val.Callee.(*aster.IdentExpr); ok {
					targetFunc := cg.findFunc(callIdent.Name)
					if targetFunc != nil && targetFunc.Return != nil && len(targetFunc.Return.Fields) > 1 {
						typeName = cg.getEnvelopeName(targetFunc.FuncName)
					} else if callIdent.Type != nil {
						typeName = cg.mapType(callIdent.Type)
					}
				}
			case *aster.StructLiteral:
				if val.Type != nil {
					typeName = val.Type.Name
				}
			case *aster.FieldAccessExpr:
				// Direct field access check without requiring objIdent or unmapped AST references
				if val.Field != "" && cg.CurrentFunction != nil && cg.CurrentFunction.Return != nil {
					// Check available function return fields for matching field type
					for _, f := range cg.CurrentFunction.Return.Fields {
						if f.Name == val.Field {
							typeName = cg.mapType(f.Type)
							break
						}
					}
				}
			}
		}

		fmt.Fprintf(&cg.sourceStream, "%s %s = ", typeName, ident.Name)
		cg.genExpr(s.Value)
		cg.sourceStream.WriteString(";\n")
	}
}

func (cg *Codegen) genVarDeclarStmt(s *aster.VarDeclar) {
	cg.writeIndent()
	cType := cg.mapType(s.Type)
	if s.Type != nil && s.Type.IsArray {
		fmt.Fprintf(&cg.sourceStream, "%s %s[%d];\n", cType, s.Name, s.Type.Size)
	} else {
		if s.Value != nil {
			if structLit, ok := s.Value.(*aster.StructLiteral); ok && s.Type.PtrDepth > 0 {
				cg.genHeapStructLiteral(structLit, s.Name)
			} else {
				fmt.Fprintf(&cg.sourceStream, "%s %s = ", cType, s.Name)
				cg.genExpr(s.Value)
				cg.sourceStream.WriteString(";\n")
			}
		} else {
			fmt.Fprintf(&cg.sourceStream, "%s %s;\n", cType, s.Name)
		}
	}
}

func (cg *Codegen) genAssignStmt(s *aster.Assign) {
	if len(s.Targets) == 0 {
		return
	}

	// 1. If single target, generate simple assignment directly
	if len(s.Targets) == 1 {
		cg.writeIndent()
		cg.genExpr(s.Targets[0])
		cg.sourceStream.WriteString(" = ")
		cg.genExpr(s.Value)
		cg.sourceStream.WriteString(";\n")
		return
	}

	// 2. If multiple targets, handle multi-assignment by iterating over all targets
	// (Assumes RHS evaluates to a multi-return struct/envelope or tuple extraction)
	for i, target := range s.Targets {
		cg.writeIndent()
		cg.genExpr(target)
		cg.sourceStream.WriteString(" = ")

		// If RHS is a function call or tuple, extract the corresponding field ._0, ._1, etc.
		cg.genExpr(s.Value)
		fmt.Fprintf(&cg.sourceStream, "._%d;\n", i)
	}
}
func (cg *Codegen) genExprStmt(s *aster.ExprStmt) {
	cg.writeIndent()
	cg.genExpr(s.Expr)
	if _, isDecl := s.Expr.(*aster.Declar); !isDecl {
		cg.sourceStream.WriteString(";\n")
	}
}

func (cg *Codegen) genReturnStmt(s *aster.ReturnStmt) {
	if cg.CurrentFunction != nil && cg.CurrentFunction.Return != nil && len(cg.CurrentFunction.Return.Fields) > 0 {

		if len(cg.CurrentFunction.Return.Fields) == 1 && !cg.CurrentFunction.Return.HasError {
			cg.writeIndent()
			cg.sourceStream.WriteString("return ")
			if len(s.Results) > 0 {
				cg.genExpr(s.Results[0])
			}
			cg.sourceStream.WriteString(";\n")
			return
		}

		envelopeName := cg.getEnvelopeName(cg.CurrentFunction.FuncName)

		if len(s.Results) == 1 && len(cg.CurrentFunction.Return.Fields) > 1 {
			cg.writeIndent()
			cg.sourceStream.WriteString("return ")
			cg.genExpr(s.Results[0])
			cg.sourceStream.WriteString(";\n")
			return
		}

		cg.writeIndent()
		fmt.Fprintf(&cg.sourceStream, "%s __ret_env = {0};\n", envelopeName)

		if len(s.Results) == 0 {
			for i, field := range cg.CurrentFunction.Return.Fields {
				fieldName := field.Name
				if fieldName == "" {
					fieldName = fmt.Sprintf("_%d", i)
				}
				cg.writeIndent()
				fmt.Fprintf(&cg.sourceStream, "__ret_env.%s = %s;\n", fieldName, fieldName)
			}
		} else {
			for i, expr := range s.Results {
				if i < len(cg.CurrentFunction.Return.Fields) {
					fieldName := cg.CurrentFunction.Return.Fields[i].Name
					if fieldName == "" {
						fieldName = fmt.Sprintf("_%d", i)
					}
					cg.writeIndent()
					fmt.Fprintf(&cg.sourceStream, "__ret_env.%s = ", fieldName)
					cg.genExpr(expr)
					cg.sourceStream.WriteString(";\n")
				}
			}
		}

		cg.writeIndent()
		cg.sourceStream.WriteString("return __ret_env;\n")
	} else {
		cg.writeIndent()
		cg.sourceStream.WriteString("return;\n")
	}
}

func (cg *Codegen) genForStmt(s *aster.ForStmt) {
	cg.writeIndent()
	cg.sourceStream.WriteString("for (")

	if s.Init != nil {
		switch initStmt := s.Init.(type) {
		case *aster.Assign:
			if len(initStmt.Targets) > 0 {
				cg.genExpr(initStmt.Targets[0])
				cg.sourceStream.WriteString(" = ")
				cg.genExpr(initStmt.Value)
			}
		case *aster.Declar:
			if len(initStmt.Targets) > 0 {
				cg.sourceStream.WriteString("int32_t ")
				cg.genExpr(initStmt.Targets[0])
				cg.sourceStream.WriteString(" = ")
				cg.genExpr(initStmt.Value)
			}
		}
	}

	cg.sourceStream.WriteString("; ")
	if s.Cond != nil {
		cg.genExpr(s.Cond)
	}
	cg.sourceStream.WriteString("; ")
	if s.Post != nil {
		if assign, ok := s.Post.(*aster.Assign); ok {
			if len(assign.Targets) > 0 {
				cg.genExpr(assign.Targets[0])
				cg.sourceStream.WriteString(" = ")
				cg.genExpr(assign.Value)
			}
		}
	}
	cg.sourceStream.WriteString(") ")
	cg.genBlock(s.Body)
}
